name: FeatherFlight
main: me.jorislight.featherflight.FeatherFlight
version: 1.5
description: Flight with luxury feathers

author: Pixel

commands:
    fly:
      description: Enables/Disables flight
      usage: /<command> [player]
      aliases: [f, flight]
permissions:
    featherflight.*:
        description: Gives access to complete flight
        children:
            featherflight.fly: true
            featherflight.fly.others: true
    featherflight.fly:
        description: Allows the player to fly
        default: op
    featherflight.fly.others:
        description: Allows the player to change other players' flight
        default: op